title = "Plain Code"
baseURL = "https://plaincoding.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

publishDir = "docs"
[params]
  author = "Sang Cu"
  description = "Plain coding"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "themes by Olivier Roques"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1  
  [[menu.main]]
    name = "Articles"
    url = "/articles"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
